name: CI

on:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      - name: Install reportgenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Combine Coverage Reports
        run: reportgenerator -reports:./**/coverage.cobertura.xml -targetdir:./coverage -reporttypes:Cobertura
      - name: Parse Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "./coverage/Cobertura.xml"
          badge: true
          format: markdown
          hide_complexity: true
          indicators: false
          output: both
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
