name: Dev deployment

on:
  push:
    branches: ["dev"]

env:
  PROJECT_ID: apsitvarkom-dev
  GAR_LOCATION: us-east1
  REPOSITORY: docker-apsitvarkom-dev
  IMAGE: apsitvarkom-fe

jobs:
  build-test-publish-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release Apsitvarkom.Api

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.DELIVERY_SERVICE_ACCOUNT }}"
          token_format: "access_token"

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest"
